version: '3.4'
volumes:
  data:
services:
  restfullmysqlwithaspnetcoreanddocker:
    image: restfullmysqlwithaspnetcoreanddocker
    build:
      context: .
      dockerfile: RESTFullMySQLWithASPNETCoreAndDocker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1307:1307"
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=rest_with_asp_net_udemy
      - MYSQL_ROOT_PASSWORD=
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1