version: '2'
services:
  jod:
    image: guilhermeadc/sei3_jod-2.2.2
    container_name: jod
    ports:
      - "8080:8080"

  smtp:
      image: guilhermeadc/sei3_mailcatcher
      container_name: smtp
      ports:
        - "1080:1080"

  memcached:
    image: guilhermeadc/sei3_memcached
    container_name: memcached
    ports:
      - "11211:11211"

  mysql:
    image: guilhermeadc/sei3_mysql-5.6
    container_name: mysql
    ports:
      - "3306:3306"

#  oracle:
#    image: guilhermeadc/sei3_oracle-11g
#    container_name: oracle
#    ports:
#      - "1521:1521"

#  sqlserver:
#    image: guilhermeadc/sei3_sqlserver-2017
#    container_name: sqlserver
#    ports:
#      - "1433:1433"

  solr:
    image: guilhermeadc/sei3_solr-6.1
    container_name: solr
    ports:
      - "8983:8983"

  http:
    image: guilhermeadc/sei3_httpd-2.4
    container_name: httpd
    dns: "8.8.8.8"
    ports:
      - "80:80"
    volumes:
      - /mnt/sei/src:/opt
    environment:
      - SEI_HOST_URL=http://localhost      
    links:
      - mysql:mysql
#      - oracle:oracle
#      - sqlserver:sqlserver
      - memcached:memcached
      - solr:solr
      - smtp:smtp
      - jod:jod
