version: '3'

services:
  siteheroismarvel:
    image: siteheroismarvel
    build:
      context: .
    ports:
      - "20000:80"
    networks:
      - marvel-network
    depends_on:
      - "redisheroismarvel"

  redisheroismarvel:
    image: redis:alpine
    ports:
      - "16379:6379"
    networks:
      - marvel-network

networks: 
    marvel-network:
        driver: bridge