version: '3.4'

services:
  db:
    image: erudio-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile    
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - "3306:3306"
    networks:
      - erudio-network

  restfullmysqlwithaspnetcoreanddocker:
    image: restfullmysqlwithaspnetcoreanddocker-api
    build:
      context: .
      dockerfile: RESTFullMySQLWithASPNETCoreAndDocker/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      HOST: db
      DB_USER: root
      DB_PWD: user
    ports:
      - "80"
    links:
      - db
    depends_on:
      - db
    networks:
      - erudio-network

networks: 
    erudio-network:
        driver: bridge
