version: '3.4'

services:
  db:
    image: erudio-mysql
    entrypoint: ['/init_database.sh', '--default-authentication-plugin=mysql_native_password']
    restart: always
    volumes:
      - "./RESTFullMySQLWithASPNETCoreAndDocker/ci/init_database.sh:/usr/local/bin/init_database.sh"
    build:
      context: .
      dockerfile: Dockerfile    
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - "3306:3306"
    networks:
      - erudio-network

  restfullmysqlwithaspnetcoreanddocker:
    image: restfullmysqlwithaspnetcoreanddocker-api
    build:
      context: .
      dockerfile: RESTFullMySQLWithASPNETCoreAndDocker/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      HOST: db
      DB_USER: root
      DB_PWD: user
    ports:
      - "80"
    links:
      - db
    depends_on:
      - db
    networks:
      - erudio-network

networks: 
    erudio-network:
        driver: bridge
